name: deploy

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  move:
    # Name the Job
    name: Move to droplet
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Copy to destination
        uses: horochx/deploy-via-scp@master
        with:
          local: README.md # eg: dist/*
          remote: /files # eg: /home/github-action/www
          host: ${{ secrets.CLOUD_IP }} # eg: example.com
          port: 22 # eg: 22
          user: root # eg: github-action
          key: ${{ secrets.CLOUD_KEY }}